### ISSUE TITLE
How do you get this repo to run? I want it so bad!!

### ISSUE THREAD

**Issue by RickRyan26** [semicognitive/sveltekit-modal-langchain#2]
Desperately trying to get https://github.com/semicognitive/sveltekit-modal-langchain to run. I know a ton about SvelteKit and node but can't get Python to run for the life of me. Below is the furthest I've gotten (using WSL2) but I have also tried on Windows 11 and Ubuntu 22 and can't get modal to do anything but create a token... Thank you for any thoughts you have!

rr26@RACKY:~/sveltekit-modal-langchain$ npm run dev

> sveltekit-modal-langchain@0.0.1 dev
> vite dev

  VITE v4.3.9  ready in 609 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /usr/lib/python3.10/runpy.py:196 in _run_module_as_main                                          │
│                                                                                                  │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│                                                                                                  │
│ /usr/lib/python3.10/runpy.py:86 in _run_code                                                     │
│                                                                                                  │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│                                                                                                  │
│ /home/rr26/sveltekit-modal-langchain/node_modules/sveltekit-modal/esm/src/vite/sveltekit_modal/s │
│ erve.py:5 in <module>                                                                            │
│                                                                                                  │
│    4 from modal.cli.import_refs import import_stub                                               │
│ ❱  5 from modal._live_reload import run_serve_loop                                               │
│    6                                                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'modal._live_reload'
rr26@RACKY:~/sveltekit-modal-langchain$ npm run build

> sveltekit-modal-langchain@0.0.1 build
> vite build

error during build:
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:405:5)
    at new URL (node:internal/url:743:13)
    at configResolved (file:///home/rr26/sveltekit-modal-langchain/node_modules/sveltekit-modal/esm/src/vite/mod.js:84:25)
    at file:///home/rr26/sveltekit-modal-langchain/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:64256:28
    at Array.map (<anonymous>)
    at resolveConfig (file:///home/rr26/sveltekit-modal-langchain/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:64256:14)
    at async build (file:///home/rr26/sveltekit-modal-langchain/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46318:20)
    at async CAC.<anonymous> (file:///home/rr26/sveltekit-modal-langchain/node_modules/vite/dist/node/cli.js:812:9)

**Comment by ConProgramming** [comment]
Hey! Modal keeps changing their internal code of their library :/

I described below which version works solid... will update the package for latest version soon though 

https://github.com/semicognitive/sveltekit-modal/issues/4

**Comment by RickRyan26** [comment]
DOPE!!! Looking forward to trying this when I get back to my computer. Thanks!

EDIT: Tried the older version and it simply led to more errors

**Comment by RickRyan26** [comment]
When someone gets the repo running on either Windows, Ubuntu, Docker, WSL2, or similar please let me know! I tried them all and hit different errors with each

**Comment by michaelcuneo** [comment]
> When someone gets the repo running on either Windows, Ubuntu, Docker, WSL2, or similar please let me know! I tried them all and hit different errors with each

I'm almost there... I've been rebuilding it all afternoon.

**Comment by michaelcuneo** [comment]
#https://github.com/semicognitive/sveltekit-modal/issues/9#issue-2146491130
